# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-31 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180831_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='txt_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
