# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_documents_txt_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='href',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
