# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_documents_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='uid',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
    ]
