# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_documents_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
