# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_documentcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcontent',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
