# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-04 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_documentcontent_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcontent',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documents',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
    ]
