# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20180904_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('html', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='documents',
            name='is_file_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='files',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Documents'),
        ),
    ]
