# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20180910_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('cnt', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='documents',
            name='doc_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='doc_txt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='is_document_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documents',
            name='is_files_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documents',
            name='list_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documents',
            name='list_txt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='files',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='files',
            name='txt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
