# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20180910_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcontent',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='page',
        ),
        migrations.DeleteModel(
            name='DocumentContent',
        ),
    ]
