# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180910_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='cnt',
            field=models.CharField(blank=True, default=0, max_length=25, null=True),
        ),
    ]
