# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-10 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20180910_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='files',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
