# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-04 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20180917_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Documents'),
        ),
    ]
